### ISSUE TITLE
Support using a TOML "dotfile" config file in the user's home directory

### ISSUE THREAD

**Issue by cduarte3** [ajogseneca/DocBot#11]
# New Feature

For this new feature I will be adding support for a TOML "dotfile" to be used from the user's home directory.
A TOML file to be used will contain default options for the program to use.
Anything not recognized by DocBot will be ignored from the file.

**Comment by ajogseneca** [comment]
Thank you for implementing this feature in my tool. The new implementation is working as expected. This will make my tool faster by enabling users to add a pre-set TOML file to make use of all command-line arguments that my tool offers.
